# Site settings
title: JJF'S BLOG
SEOTitle: 焦江峰的博客 | JJF'S BLOG
header-img: img/post-bg-desk.jpg
email: jaychou19961107@gmail.com
description: "永远相信美好的事情即将发生"
keyword: "JF, JJF Blog, 焦江峰的博客, JJF, 焦江峰, Date, Python"
url: "http://jiaojiangfeng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jiaojiangfeng/jiaojiangfeng.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Say what you mean Do what you say"
sidebar-avatar: /img/about-JJF.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     jiao-jiang-feng
github_username:    jiaojiangfeng
facebook_username:  chou.jay.31337
jianshu_username:   
twitter_username:   jiaojiangfeng




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 9d941f7996d81dfbb7b4                         #生成的clientID
  clientSecret: 99062f9a01308f740dc3ecfed0a7587c64c0c8e7  #生成的clientSecret
  repo: jiaojiangfeng.github.io    #仓库名称
  owner: jiaojiangfeng    #github用户名
  admin: jiaojiangfeng
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-135903662-2'            # Format: UA-xxxxxx-xx
ga_domain: jiaojfeng.com          # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "MokeDc",
        href: "https://mokedc.tw/"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Android",
        href: "https://www.android.com/"
    },{
        title: "Python",
        href: "https://www.python.org/"
    }
]
